services:
  postgres:
    image: postgres:17
    container_name: gympass
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: gympass
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: gympass-redis
    ports:
      - "6379:6379"
